from __future__ import annotations

from .schemas import ReportDto, StudyDto

MOCK_REPORT = ReportDto(
    reportId=1001,
    title="Vitamin D and bone density in older adults",
    authors=["A. Smith","B. Lee"],
    year=2022,
    abstract="We evaluate bone density outcomes after vitamin D supplementation in older adults.",
    trialId="NCT01234567",
)

MOCK_STUDIES = [
    StudyDto(
        StatusofStudy="Completed",
        NumberParticipants="180",
        TrialistContactDetails=None,
        Countries="US",
        CENTRALSubmissionStatus="Submitted",
        Duration="9 months",
        Notes=None,
        UDef4=None,
        CRGStudyID=2003,
        DateEntered="2022-06-20",
        Comparison="Vitamin D plus calcium vs placebo",
        CENTRALStudyID=5003,
        ISRCTN="ISRCTN99887766",
        ShortName="Vitamin D and calcium in older adults",
        DateEdited="2022-08-01",
        UDef6=None,
        Search_Tagged=False,
        TrialRegistrationID="NCT09876543",
    ),
    StudyDto(
        StatusofStudy="Completed",
        NumberParticipants="150",
        TrialistContactDetails=None,
        Countries="UK",
        CENTRALSubmissionStatus="Submitted",
        Duration="6 months",
        Notes=None,
        UDef4=None,
        CRGStudyID=2002,
        DateEntered="2021-09-10",
        Comparison="High fiber vs standard diet",
        CENTRALStudyID=5002,
        ISRCTN="ISRCTN87654321",
        ShortName="Dietary fiber and microbiome",
        DateEdited="2021-11-02",
        UDef6=None,
        Search_Tagged=False,
        TrialRegistrationID="NCT07654321",
    ),
    StudyDto(
        StatusofStudy="Completed",
        NumberParticipants="200",
        TrialistContactDetails=None,
        Countries="US; Canada",
        CENTRALSubmissionStatus="Submitted",
        Duration="12 months",
        Notes=None,
        UDef4=None,
        CRGStudyID=2001,
        DateEntered="2022-12-01",
        Comparison="Vitamin D vs placebo",
        CENTRALStudyID=5001,
        ISRCTN="ISRCTN12345678",
        ShortName="Vitamin D bone density trial",
        DateEdited="2023-01-15",
        UDef6=None,
        Search_Tagged=False,
        TrialRegistrationID="NCT01234567",
    ),
    StudyDto(
        StatusofStudy="Completed",
        NumberParticipants="220",
        TrialistContactDetails=None,
        Countries="Canada",
        CENTRALSubmissionStatus="Submitted",
        Duration="10 months",
        Notes=None,
        UDef4=None,
        CRGStudyID=2004,
        DateEntered="2021-03-12",
        Comparison="Resistance training vs usual care",
        CENTRALStudyID=5004,
        ISRCTN="ISRCTN44556677",
        ShortName="Resistance training for fall prevention",
        DateEdited="2021-04-20",
        UDef6=None,
        Search_Tagged=False,
        TrialRegistrationID="NCT05554444",
    ),
    StudyDto(
        StatusofStudy="Completed",
        NumberParticipants="90",
        TrialistContactDetails=None,
        Countries="US",
        CENTRALSubmissionStatus="Submitted",
        Duration="4 months",
        Notes=None,
        UDef4=None,
        CRGStudyID=2005,
        DateEntered="2020-05-12",
        Comparison="Omega-3 supplement vs placebo",
        CENTRALStudyID=5005,
        ISRCTN="ISRCTN11112222",
        ShortName="Omega-3 and cognitive outcomes",
        DateEdited="2020-06-15",
        UDef6=None,
        Search_Tagged=False,
        TrialRegistrationID="NCT01112223",
    ),
    StudyDto(
        StatusofStudy="Completed",
        NumberParticipants="110",
        TrialistContactDetails=None,
        Countries="Germany",
        CENTRALSubmissionStatus="Submitted",
        Duration="8 months",
        Notes=None,
        UDef4=None,
        CRGStudyID=2006,
        DateEntered="2021-01-08",
        Comparison="Vitamin B12 vs placebo",
        CENTRALStudyID=5006,
        ISRCTN="ISRCTN33334444",
        ShortName="Vitamin B12 and anemia in older adults",
        DateEdited="2021-02-20",
        UDef6=None,
        Search_Tagged=False,
        TrialRegistrationID="NCT03334445",
    ),
    StudyDto(
        StatusofStudy="Completed",
        NumberParticipants="140",
        TrialistContactDetails=None,
        Countries="UK",
        CENTRALSubmissionStatus="Submitted",
        Duration="12 months",
        Notes=None,
        UDef4=None,
        CRGStudyID=2007,
        DateEntered="2022-04-18",
        Comparison="Calcium plus exercise vs exercise alone",
        CENTRALStudyID=5007,
        ISRCTN="ISRCTN55556666",
        ShortName="Exercise and calcium for bone density",
        DateEdited="2022-06-01",
        UDef6=None,
        Search_Tagged=False,
        TrialRegistrationID="NCT05556667",
    ),
    StudyDto(
        StatusofStudy="Completed",
        NumberParticipants="175",
        TrialistContactDetails=None,
        Countries="US",
        CENTRALSubmissionStatus="Submitted",
        Duration="12 months",
        Notes=None,
        UDef4=None,
        CRGStudyID=2008,
        DateEntered="2022-09-25",
        Comparison="Vitamin D supplementation vs placebo",
        CENTRALStudyID=5008,
        ISRCTN="ISRCTN77778888",
        ShortName="Vitamin D supplementation in older adults",
        DateEdited="2022-10-30",
        UDef6=None,
        Search_Tagged=False,
        TrialRegistrationID="NCT07778889",
    ),
    StudyDto(
        StatusofStudy="Completed",
        NumberParticipants="190",
        TrialistContactDetails=None,
        Countries="US; Canada",
        CENTRALSubmissionStatus="Submitted",
        Duration="10 months",
        Notes=None,
        UDef4=None,
        CRGStudyID=2009,
        DateEntered="2022-11-05",
        Comparison="Vitamin D plus calcium vs placebo",
        CENTRALStudyID=5009,
        ISRCTN="ISRCTN99990000",
        ShortName="Vitamin D plus calcium for bone density",
        DateEdited="2022-12-20",
        UDef6=None,
        Search_Tagged=False,
        TrialRegistrationID="NCT09990001",
    ),
    StudyDto(
        StatusofStudy="Completed",
        NumberParticipants="210",
        TrialistContactDetails=None,
        Countries="US; Canada",
        CENTRALSubmissionStatus="Submitted",
        Duration="12 months",
        Notes=None,
        UDef4=None,
        CRGStudyID=2010,
        DateEntered="2023-01-02",
        Comparison="Vitamin D vs placebo",
        CENTRALStudyID=5010,
        ISRCTN="ISRCTN12121212",
        ShortName="Vitamin D and bone density in older adults (replication)",
        DateEdited="2023-02-01",
        UDef6=None,
        Search_Tagged=False,
        TrialRegistrationID="NCT01234568",
    ),
]
